v1.2.18 fix: GitAutomation chore: Version number v1.2.18

diff --git a/.github/workflows/update-gist.yml b/.github/workflows/update-gist.yml
--- a/.github/workflows/update-gist.yml
+++ b/.github/workflows/update-gist.yml
@@ -12,14 +12,36 @@ jobs:
         id: vars
         shell: pwsh
         run: |
+          $owner, $repository = "${{ github.repository }}" -split '/'
           $VerbosePreference = 'Continue'
           $tagName = "${{ github.event.release.tag_name }}"
-          Write-Verbose "Release tag name: $tagName"
           $version = $tagName -replace '^v'
-          $isPreRelease = ${{ github.event.release.prerelease }}
-          Write-Verbose "PreRelease: $isPreRelease"
-          $channel = if ($isPreRelease) { 'dev' } else { 'stable' }
-          Write-Verbose "Determined channel: $channel"
+
+          Write-Host "Tag Name: $tagName"
+          Write-Host "Version: $version"
+
+          $ReleaseUrl = "https://api.github.com/repos/$($owner)/$($repository)/releases/tags/$($tagName)"
+          $Headers = @{
+              "Accept" = "application/vnd.github+json"
+              "Authorization" = "Bearer ${{ secrets.GITHUB_TOKEN }}"
+              "X-GitHub-Api-Version" = "2022-11-28"
+          }
+          try {
+              $ReleaseData = Invoke-RestMethod -Uri $ReleaseUrl -Headers $Headers
+              $IsPrerelease = $ReleaseData.prerelease
+
+              Write-Host "Release: '$tagName'; Pre-release: $IsPrerelease"
+
+              if ($IsPrerelease) {
+                  $channel = 'dev'
+              } else {
+                  $channel = 'stable'
+              }
+              Write-Verbose "Determined channel: $channel"
+          } catch {
+              Write-Error "Failed to retrieve release information for '$tagName'. Error: $($_.Exception.Message)"
+              exit 1
+          }
           echo "version=$version" >> $env:GITHUB_OUTPUT
           echo "channel=$channel" >> $env:GITHUB_OUTPUT
           Write-Host "Processing Release: $tagName, Version: $version, Channel: $channel"
@@ -29,12 +51,11 @@ jobs:
         env:
           PAT_TOKEN: ${{ secrets.GIST_PAT }}
           GIST_ID: "27a5c52571bddc7eff4ea21f407d4e71"
-          GIST_USER: "j81blog"
           GIST_FILE: "versioninfo.json"
         run: |
-          $gistRawUrl = "https://gist.githubusercontent.com/$($env:GIST_USER)/$($env:GIST_ID)/raw/"
+          $owner, $repository = "${{ github.repository }}" -split '/'
+          $gistRawUrl = "https://gist.githubusercontent.com/$($owner)/$($env:GIST_ID)/raw/"
           $VerbosePreference = 'Continue'
-          $owner, $repository = $env:GITHUB_REPOSITORY -split '/'
           try {
               Write-Host "Fetching and parsing JSON from $($gistRawUrl)"
               $json = Invoke-RestMethod -Uri $gistRawUrl -ErrorAction Stop
